### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by BI7PRK** [c0shea/AdminLTE-Template#1]
I have successfully installed, but can not find to use it.

**Comment by c0shea** [comment]
Once you've installed the extension for Visual Studio, navigate to File > New > Project. On the left under Installed Templates, select Visual C#. In the middle list you should then see AdminLTE with a blue icon towards the bottom of the list. Give the project a name and location and click OK. That will create a new C# MVC project with all the necessary pieces you need. Press F5 to build and run and you should be good to go.

**Comment by BI7PRK** [comment]
Great job. If it can be create in the MVC area, It is more perfect.

**Comment by c0shea** [comment]
Thanks. If I get a chance when the next major update to AdminLTE is released I'll try to rework the template so it shows up under the web/MVC section and not just at the root of C#.
