### ISSUE TITLE
Update to AdminLTE v2.4.0

### ISSUE THREAD

**Issue by iprida** [c0shea/AdminLTE-Template#10]
Update to AdminLTE v2.4.0 - https://github.com/almasaeed2010/AdminLTE/releases/tag/v2.4.0

Upgrade Guide - https://adminlte.io/docs/2.4/upgrade-guide

**Comment by c0shea** [comment]
Thanks! Glad I waited a couple days since v2.4.2 was released today. You should see the updated extension in VS shortly.
