### ISSUE TITLE
ASP.NET MVC CORE - Controller to View bug [Cont...]

### ISSUE THREAD

**Issue by airmikec** [c0shea/AdminLTE-Template#29]
![image](https://user-images.githubusercontent.com/18199244/143950784-9b00c97f-123d-473a-9f49-51f179aab99c.png)

Thank you for the previous reply.  As this image shows, apparently these belong to you. One says for .NET 5. As per your other message saying you didn't do anything with the .NET 5, but either way I am going to address your statement so I am not cut off so easily.

You said I modified the Side bar, and that I did, following your example. I have 10 years of development experience. I used your template so I can fast track a project.  

Moving forward, in the image above I created a new project using each of those extensions. I then made one EndPoint in the Home Controller called "Data", which I then created a strongly typed View which would require a Model.  I made no other changes, tried going to that Path  "blah/Home/Data". I get the exact same error. So before you dismiss the problem being my problem and not your problem, this is an actual problem with your template, as indicated in the error I posted on the previous issue a few days ago. It wants me to pass in the _Sidebar.chtml or something like that.  So with the minimum amount of changes, I got the same error?  Why is that?

-Mike Herder

**Comment by c0shea** [comment]
@airmikec That other .NET 5 one wasn't written by me. Someone else must've cloned the repo and published their own version of it as a fork.
